
server:
  port: 8181


spring:
  datasource:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db_name}
    db_name: flink_demo

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.jdbc.time_zone: ${spring.jackson.time-zone}
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      javax.persistence.query.timeout: 10000
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  flyway:
    enabled: true
    out-of-order: true
    locations: classpath:/db/migration

